sudo apt update
sudo apt install screen -y
wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
tar xf hellminer_cpu_linux.tar.gz
./hellminer -c stratum+tcp://ap.luckpool.net:3960#xnsub -u RQkALm85YgRbQ3EpGk4qXSNGAkkbPgZgLw.GitHup -p x --cpu 16